services:
  db:
    image: postgres
    container_name: drizzle-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: reflink_db
    ports:
      - 5432:5432
